version: '2'
services:
    jh_instructor_demo-app:
        image: jh_instructor_demo
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jh_instructor_demo-mysql:3306/jh_instructor_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jh_instructor_demo-mysql:
        extends:
            file: mysql.yml
            service: jh_instructor_demo-mysql
